title: Predictive Brain Lab Wiki
logo: /images/pred-lab-logo.png
google_analytics:
theme: jekyll-theme-minimal
description: false

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

include:
  - index.md
  - vision-and-goals.md
