title: Predictive Brain Lab Wiki
logo: /assets/img/logo.png
description: Documentation for techincal information relevant to the lab
google_analytics:
theme: jekyll-theme-minimal

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
